// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtdnayqblfelcxaorucj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0ZG5heXFibGZlbGN4YW9ydWNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwOTMyMzIsImV4cCI6MjA3MzY2OTIzMn0.vjBc9vMogpDoFZWUWG923kCvf5JWcBm_DWh5dtMM9pw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});